import React from 'react';

const TermsAndConditions = () => {
  return (
    <div className="bg-white p-6 md:p-12 lg:p-16 max-w-7xl mx-auto text-gray-800">
      <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold mb-6">Terms and Conditions</h1>
      
      <section className="mb-8">
        <p className="mb-4">
          These Terms and Conditions govern your transactions and dealings with <strong>RELDA</strong>, This document is an electronic record under the Information Technology Act, 2000, and the rules thereunder, as applicable, and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology (Amendment) Act, 2008.
        </p>
        <p className="mb-4">
          This electronic record is generated by a computer system and does not require any physical or digital signatures. This document is published in accordance with Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011, which require the publication of rules and regulations, privacy policy, and user agreement for accessing, transacting, or using <strong>RELDA</strong>.
        </p>
        <p className="mb-4">
          The website, <strong>reldaindia.com</strong> ("Website"), is owned and operated by a proprietorship business, having its registered office at Plot No 17A, Majestic Avenue, Krishna Nagar, Madhavaram Milk Colony, Chennai, Tamilnadu 600051., hereinafter referred to as the <strong>"Company"(RELDA)</strong>.
        </p>
        <p className="mb-4">
          Use of this Website is regulated by the Terms and Conditions provided herein. Your visit, dealing, transacting, and/or otherwise using this Website shall be treated as your unconditional acceptance of these Terms and Conditions in entirety. If you do not agree with any of these Terms and Conditions, then you should stop dealing with and/or initiate any transaction on this Website.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-4">Limited Licence</h2>
        <p className="mb-4">
          We grant you a limited, non-exclusive, non-transferable, non-sub-licensable license to access and make personal and non-commercial use of the Website. All rights not expressly granted to you in these Terms of Use are reserved and retained by the Website and its affiliates. We reserve the right, at any time, without notice and at its sole discretion, to terminate your license to use the Website and to block and prevent your future access to the Website.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-4">Termination</h2>
        <p className="mb-4">
          These Terms of Use are effective unless and until terminated by either you or <strong>RELDA</strong>. You may terminate the Terms of Use at any time, provided that you discontinue any further use of this Website. We may terminate the Terms of Use at any time and may do so without notice, and accordingly deny you access to this Website, such termination will be without any liability to the Website.
        </p>
        <p className="mb-4">
          Upon any termination of the Terms of Use by either you or <strong>RELDA</strong>, you must promptly destroy all materials downloaded or otherwise obtained from this Website, as well as all copies of such materials, whether made under the Terms of Use or otherwise. Any such termination of the Terms of Use shall not cancel your obligation to pay for the product already ordered from the Website or affect any liability that may have arisen under the Terms of Use.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-4">Indemnity</h2>
        <p className="mb-4">
          You agree to defend, indemnify, and hold harmless <strong>RELDA</strong>, its employees, directors, officers, agents, and their successors and assigns, its subsidiaries, affiliates, partners, or licensors from and against any and all claims, liabilities, damages, losses, costs, and expenses, including attorney's fees, caused by or arising out of claims based upon your actions or inactions, which may result in any loss or liability to <strong>RELDA</strong> or any third party.
        </p>
        <p className="mb-4">
          This includes but is not limited to breach of any warranties, representations, or undertakings, or in relation to the non-fulfillment of any of your obligations under the Terms of Use, or arising out of your violation of any applicable laws, regulations including but not limited to Intellectual Property Rights, payment of statutory dues and taxes, claims of libel, defamation, violation of rights of privacy or publicity, loss of service by other subscribers, and infringement of intellectual property or other rights. This clause shall survive the expiry or termination of the Terms of Use.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-4">Disclaimer</h2>
        <p className="mb-4">
          The information, products, and services including but not limited to communications tools, forums, shopping services, and search services, offered on this Website or through other mediums, whether now known or hereafter developed, are solely for the User's information and subject to the User's acceptance without modification of the terms, conditions, and notices contained herein and should not be considered as a substitute for professional advice.
        </p>
        <p className="mb-4">
          The Company, its affiliate companies, associate companies, subsidiaries, consultants, contractors, advisors, employees, agents, partners, and/or suppliers assume no responsibility for any consequence relating directly and/or indirectly to any action and/or inaction that the User takes based on the information, services, Products (as defined hereinafter), and other materials offered on this Website.
        </p>
        <p className="mb-4">
          While the Company strives to keep the information relating to the various Products offered on this Website accurate, complete, and up-to-date, the Company, its subsidiaries, affiliates, associate companies, employees, advisors, agents, consultants, contractors, partners, and suppliers cannot guarantee, and will not be responsible for, any damage and/or loss related to the accuracy, completeness, or timeliness of the information.
        </p>
      </section>
    </div>
  );
};

export default TermsAndConditions;
